### PR TITLE
Greenkeeper/nan 2.14.0

### PR DESCRIPTION
**Pull request by apihlaja**
Closes #62

### CODE REVIEW

**Comment by apihlaja** [comment]
Doh, I need Windows PC to work out merge conflicts.

**Comment by apihlaja** [comment]
Now it doesn't compile with Node.js v12. And I have no idea why.. for whatever reason, ` node_modules/.bin/prebuild --target=12.0.0` gives tons of C++ syntax errors.

**Comment by apihlaja** [comment]
[C++ compiler and it's handy error messages](https://ci.appveyor.com/project/apihlaja/node-irsdk/build/job/x1o3h8eb20o6ewh4#L252):  

`c:\projects\node-irsdk\src\cpp\IrSdkBindingHelpers.h(13): error C2143: syntax error: missing ';' before '<' (compiling source file ..\src\cpp\IrSdkNodeBindings.cpp) [C:\projects\node-irsdk\build\IrSdkNodeBindings.vcxproj]`

I guess, compiler is trying to say [`Handle`](https://github.com/apihlaja/node-irsdk/blob/master/src/cpp/IrSdkBindingHelpers.h#L13) doesn't exist anymore and I should be using [`v8::Local`](https://groups.google.com/forum/#!topic/v8-users/S7_hgrH3cEo) instead.

**Comment by sabifa** [comment]
https://electronjs.org/blog/nodejs-native-addons-and-electron-5

I think you're correct about this! This electron blog post states that they removed v8::Handle for v8::Local. They also say that nodejs v12 did the same, so that should be the cause it didn't compile for you anymore.

They also say that the only thing you'd need to do is to change it to v8::Local and everything else should still work fine.

**Pull request merged**
